blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # post views
    url(r'^$', views.post_list, name='post_list'),
    # url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'\
        r'(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

from blog import views

sitemaps = {'posts': PostSitemap, }
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.home),
    url(r'^blog/',
        include('blog.urls', namespace='blog',
                app_name='blog')),
    url(r'^sitemap\.xml$',
        sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^about/$', views.about),
]

blog/models.py
# Create your models here.
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(
            status='published')


class Post(models.Model):
    objects = models.Manager()
    published = PublishedManager()
    STATUS_CHOICES = (('draft', 'Draft'),
                      ('published', 'Published'), )

    title = models.CharField('标题', max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts')
    body = models.TextField('正文')
    publish = models.DateTimeField('发布时间', default=timezone.now)
    created = models.DateTimeField('创建时间', auto_now=True)
    status = models.CharField('文章状态',
                              max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    tags = TaggableManager()

    #summary = models.CharField('摘要', max_length=54, blank=True, null=True)
    #views = models.PositiveIntegerField('浏览量', default=0)
    #likes = models.PositiveIntegerField('点赞数', default=0)
    #topped = models.BooleanField('置顶', default=False)

    class Meta:
        ordering = ('-publish', )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year, self.publish.strftime('%m'),
                             self.publish.strftime('%d'), self.slug])

blog/views.py
from django.views.generic import ListView
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.core.mail import send_mail
from django.db.models import Count

from taggit.models import Tag

from .models import Post

# Create your views here.


def home(request):
    return HttpResponseRedirect('/blog/')


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 10
    template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 10)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'posts': posts,
                                                   'page': page,
                                                   'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(
        id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by(
        '-same_tags', '-publish')[:4]
    return render(request, 'blog/post/detail.html', {'post': post,
                                                     'similar_posts':
                                                     similar_posts})


def about(request):
    return render(request, 'blog/about.html')

blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block title %}{{ "关于我" }}{% endblock %}

{% block content %}
    <div class="container">
        <ul>
            <li>重度中二患者</li>
            <li>懒癌晚期</li>
            <li>不会前端的直男癌码农一名</li>
        </ul>

    </div>
    <div class="mx-auto" style="width: 200px;">
        <a class="fa-stack fa lg" href="http://weibo.com/womeibing/" style="color:black;">
            <i class="fa fa-weibo fa-stack-2x"></i>
        </a>
        <a class="fa-stack fa lg" href="https://github.com/crasker" style="color:black;">
            <i class="fa fa-github-alt fa-stack-2x"></i>
        </a>
        <a class="fa-stack fa lg" href="https://twitter.com/winddyseed" style="color:black;">
            <i class="fa fa-twitter fa-stack-2x"></i>
        </a>
        <a class="fa-stack fa lg" href="mailto:zhouyc@knownsec.com" style="color:black;">
            <i class="fa fa-envelope fa-stack-2x"></i>
        </a>
    </div>

    <div id="disqus_thread"></div>
    <script>

     /**
      *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
      *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables */
     /*
        var disqus_config = function () {
        this.page.url = "{{ post.get_absolute_url }}";
        this.page.identifier = "{ post.get_absolute_url }}"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        };
      */
     (function() { // DON'T EDIT BELOW THIS LINE
         var d = document, s = d.createElement('script');
         s.src = '//oooooio.disqus.com/embed.js';
         s.setAttribute('data-timestamp', +new Date());
         (d.head || d.body).appendChild(s);
     })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

{% endblock %}

blog/templates/blog/base.html
{% load blog_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content/>
        <meta name="author" content/>
        <link rel="shortcut icon" type="image/png" href="{% static "favicon.ico" %}"/>
        <script src="{% static "script/prism.js" %}" async></script>
        <script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" async></script>
        <script src="//use.fontawesome.com/a4bcfd1341.js" async></script>
    </head>
    <body>
        <div class="container">
            <div class="header clearfix">
                <nav>
                    <ul class="nav nav-pills float-right">
                        <li class="nav-item">
                            <a class="nav-link {%if "blog" in request.path %}active{% endif %}" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {%if "about" in request.path %}active{% endif %}" href="/about">About</a>
                        </li>
                    </ul>
                </nav>
                <h3 class="text-muted">Rain</h3>
            </div>

            {% block content %}
            {% endblock %}

        </div> <!-- /container -->

        <!-- Bootstrap core JavaScript
             ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <link href="//cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/themes/prism-okaidia.min.css" rel="stylesheet">
        <link href="//cdn.bootcss.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" rel="stylesheet">
        <link href="{% static "css/blog.css" %}" rel="stylesheet">
        <link href="{% static "css/jumbotron-narrow.css" %}" rel="stylesheet">
    </body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h2 class="blog-post-title">{{ post.title }}</h2>
    <p class="blog-post-meta">Published {{ post.publish }} by {{ post.author }}</p>

    <div class="blog-post">
        {{ post.body|markdown }}
    </div>
    <hr/>
    <h3>Similar posts</h3>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}

    <div id="disqus_thread"></div>
    <script>

     /**
      *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
      *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables */
     /*
        var disqus_config = function () {
        this.page.url = "{{ post.get_absolute_url }}";
        this.page.identifier = "{ post.get_absolute_url }}"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        };
      */
     (function() { // DON'T EDIT BELOW THIS LINE
         var d = document, s = d.createElement('script');
         s.src = '//oooooio.disqus.com/embed.js';
         s.setAttribute('data-timestamp', +new Date());
         (d.head || d.body).appendChild(s);
     })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Rain{% endblock %}

{% block content %}
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <div class="post-list">
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </div>
        {% for tag in post.tags.all %}
            <div class="post-tag">
                <a href="{% url "blog:post_list_by_tag" tag.slug %}" class="btn btn-outline-primary btn-sm">
                    {{ tag.name }}
                </a>
            </div>
            {% if not forloop.last %} {% endif %}
        {% endfor %}
        <span style="display:block"></span>
        <hr/>
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ cd.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}

blog/templates/pagination.html
<nav class="blog-pagination">
  <span class="step-links">
    {% if page.has_previous %}
    <a class="btn btn-outline-primary" href="?page={{ page.previous_page_number }}">Previous</a>
    {% else %}
    <a class="btn btn-outline-secondary disabled" href="#">Previous</a>
    {% endif %}
    <!-- <span clas="current"> -->
    <!-- Page {{ page.number }} of {{ page.paginator.num_pages }}. -->
    <!-- </span> -->
    {% if page.has_next %}
    <a class="btn btn-outline-primary" href="?page={{ page.next_page_number }}">Next</a>
    {% else %}
    <a class="btn btn-outline-secondary disabled" href="#">Next</a>
    {% endif %}
  </span>
</nav>